### ISSUE TITLE
Schematic Mistake 

### ISSUE THREAD

**Issue by Plancksphoton** [arduino/docs-content#1092]
There's a schematic mistake on [this page](https://docs.arduino.cc/built-in-examples/analog/Calibration)
This picture: https://docs.arduino.cc/static/84cfc5d0f362e015cd99f2d085a5e7ca/29114/circuit.png
has the sensor pin connected wrong. 

Correct schematic uploaded:
![ijken sensor](https://github.com/arduino/docs-content/assets/114140078/1e40ed56-10f7-4e6b-aa3a-bb42ef836d1f)

**Comment by Hannes7eicher** [comment]
Hello @Plancksphoton.

Good catch and thanks for the contribution. I fixed the circuit with [here](https://github.com/arduino/docs-content/pull/1747).
