### ISSUE TITLE
List intended to be a numbered list wrong on Chrome

### ISSUE THREAD

**Issue by Sgeo** [arduino/docs-content#1117]
https://docs.arduino.cc/tutorials/uno-rev3/board-anatomy

On Chrome and Firefox, each bullet point is showing up as 1, making it hard to interpret.

**Comment by Sgeo** [comment]
![image](https://github.com/arduino/docs-content/assets/251161/4300883d-9816-48ff-95d1-93840fccc93b)

**Comment by AdamRaichu** [comment]
Issue still present.

**Comment by sebromero** [comment]
@jacobhylen Could you please take a look? 🙏 cc @jhansson-ard
