### ISSUE TITLE
CAN Tutorial VD230

### ISSUE THREAD

**Issue by stijnb1234** [arduino/docs-content#1119]
The CAN tutorial for the Arduino Uno R4 mentions the SN65HVD230 transceiver will be used and that it should be connected to 5V, but this module is designed for 3.3V.

![image](https://github.com/arduino/docs-content/assets/27051051/a82e10f3-aa36-4607-96a8-20ccce9fcabc)

https://docs.arduino.cc/tutorials/uno-r4-wifi/can

**Comment by karlsoderby** [comment]
Hi there @stijnb1234 , that is correct. I will make an update to this tutorial. Thank you for reporting!

**Comment by stijnb1234** [comment]
Thanks! The pins are also different from the generic pinout chart. Please check that out too.
