### ISSUE TITLE
#include <Morse.h>

### ISSUE THREAD

**Issue by bsbhro** [arduino/docs-content#114]
I got the compilation error 'No such file...', though the file Morse.h is in the same folder. I sat quotes #include "Morse.h" . So it ran. Is my installation missing a library path? I use v.1.8.19.

Oh, a bit later I saw the v. 2.rc5 gives the hint to set quotes. There is always the question how the author did it with <>?

**Comment by karlsoderby** [comment]
Hi @bsbhro, thanks for reporting! I believe you are referring to https://docs.arduino.cc/hacking/software/LibraryTutorial.

The difference between using `""` and `<>` for including files, is that the first looks only in the current directory, and the latter to look for it in a pre-designated folder (libraries). So this is why it uses `#include <"Morse.h">`. I hope that helps explain it a bit!

**Comment by bsbhro** [comment]
Thank you!
