### ISSUE TITLE
add that zero ohm resistors for USB HS are missing on Portenta Breakout board

### ISSUE THREAD

**Issue by Flydroid** [arduino/docs-content#123]
Hi,

While using the portenta breakout board we have noticed that there are three zero ohm resistors (R6, R7,R8) missing to connect the USB HS from the portenta to the pinout on the breakout board. 
Its not clear why those are missing - maybe just forgotten in the production documents?

on the board - no resistors mounted!
![image](https://user-images.githubusercontent.com/6762933/160400115-a0a63f8b-c9c4-4bce-8aa1-32844f55106d.png)

on schematic
![image](https://user-images.githubusercontent.com/6762933/160400183-e9f02c57-7e2e-4025-9ed7-0864f23e8edb.png)

**Comment by marqdevx** [comment]
Hey! @Flydroid Thanks for letting us know!

Your board is fine, Im going to update the schematics and documentation, the schematics should show the following:
![image](https://user-images.githubusercontent.com/11246294/160555737-b3143f0c-7cec-40e7-a58b-4de60ff2fa09.png)

I will create a PR and make you reviewer, feel free to give us your feedback! :D

In case you want to connect those pads, you can do it by soldering a 0ohm resistor or a wire/copper.

**Comment by Flydroid** [comment]
Awesome!
But is there a reason why it's not mounted? Interference when using the normal USB connector? 

Yes that's we did!

**Comment by marqdevx** [comment]
PR ready #153

**Comment by pnndra** [comment]
@Flydroid sorry for the slow reply. the reason why those jumper resistors are not mounted is that those USB lines are the same that go to the on board USB-C connector. if we had those mounted they would create a stub on the traces and may interfere with normal USB-C operation. 
if you intend to use that port from the breakout you have to short those pads AND use the USB only from breakout, leaving USB-C unconnected.

**Comment by marqdevx** [comment]
Merged, closing the issue.
Thanks for the report!
