### ISSUE TITLE
Add a code of conduct?

### ISSUE THREAD

**Issue by V205Arduino** [arduino/docs-content#1297]
Add a code of conduct?
Feedback?

**Comment by jcarolinares** [comment]
Hello

Which kind of code of conduct are you looking for? In case yo are referring to the Arduino Forum I'm afraid this is not the right repository. This repository is related to the official Arduino Documentation. Please do this request again at the forum, thanks

Closing.

**Comment by V205Arduino** [comment]
Thank you, was intending for this to be for the repository, but thanks anyways!
I believe the forum already has a CoC.
