### ISSUE TITLE
attachInterrupt() documentation is missing the Nano ESP32, Nano RP2040 Connect and UNO R4s

### ISSUE THREAD

**Issue by runger1101001** [arduino/docs-content#1323]
The documentation for attachInterrupt is missing information on these boards:

- Nano RP2040 Connect
- Nano ESP32
- UNO R4 Minima
- UNO R4 WiFi

**Comment by karlsoderby** [comment]
Hi @runger1101001 , thank you for the submission. 

I have updated the UNO R4 Minima & WiFi documentation in this PR: 
- https://github.com/arduino/docs-content/pull/1325

I have also updated the `attachInterrupt()` page, adding the missing boards. You can see it in this PR:
- https://github.com/arduino/reference-en/pull/926

Changes will be live in some hours!
