### ISSUE TITLE
The example code in the Arduino UNO R4 WiFi Real-Time Clock document is incorrect and misleading

### ISSUE THREAD

**Issue by eMUQI** [arduino/docs-content#1351]
Hello everyone, when I tried to run the example in https://docs.arduino.cc/tutorials/uno-r4-wifi/rtc#Periodic-Interrupt, I found some errors in it. 

https://github.com/arduino/docs-content/blob/67c3aa5aa5c53ff492704ee90a675dddd74b464e/content/hardware/02.hero/boards/uno-r4-wifi/tutorials/rtc/rtc.md?plain=1#L177-L216

Here are some issues I believe exist in the code and my suggestions:

1. **Pin error**, Arduino R4 onboard LED is `13` or `LED_BUILTIN`, but code uses `22`.
2. **Missing `Serial.begin(9600);`.**
3. **Missing `RTC.setTime()`.** According to [RTC_PeriodicExample.ino]( https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/RTC/examples/RTC_PeriodicExample/RTC_PeriodicExample.ino)  `RTC.setTime()` must be called for `RTC.setPeriodicCallback` to work.
4. **Using camel case naming convention and more intuitive naming methods would be better.**  Refer to the [Arduino Style Guide for Creating Libraries](https://docs.arduino.cc/learn/contributions/arduino-library-style-guide). The code mixes camel case naming convention and underscore naming convention. And names like `periodic_cbk` and `clb_st` confuse me, perhaps it would be better to not use abbreviations and instead use `periodicCallback` and `callbackStatus`?
https://github.com/arduino/docs-content/blob/67c3aa5aa5c53ff492704ee90a675dddd74b464e/content/learn/08.contributions/01.arduino-library-style-guide/arduino-library-style-guide.md?plain=1#L17 https://github.com/arduino/docs-content/blob/67c3aa5aa5c53ff492704ee90a675dddd74b464e/content/learn/08.contributions/01.arduino-library-style-guide/arduino-library-style-guide.md?plain=1#L31
5. The final suggestion was made by Arduino users [van_der_decken](https://forum.arduino.cc/t/there-may-be-some-conflict-between-rtc-and-the-serial/1169836/3) and [ubidefeo](https://forum.arduino.cc/t/there-may-be-some-conflict-between-rtc-and-the-serial/1169836/6). "It is not recommended to perform lengthy operations within interrupts." "The proper way to use IRQs is generally by setting a flag that will be checked inside your loop." **Putting `serial.println()` inside `periodicCallback()` doesn't seem like a wise decision, the code in the example can mislead someone like me who is unfamiliar with rtc.**

I also reported this issue on the Arduino community forum, see https://forum.arduino.cc/t/there-may-be-some-conflict-between-rtc-and-the-serial/1169836.

Another related issue is: https://github.com/arduino/ArduinoCore-renesas/issues/138

I hope the document can be improved. Thank you for reading this issue!

**Comment by karlsoderby** [comment]
Hi @eMUQI . We have updated the RTC tutorial with regard to the feedback you left here, and using the example provided by Ubi in the forum thread. Thanks for reporting it in such detail. 

PR for docs update: https://github.com/arduino/docs-content/pull/1370

**Comment by eMUQI** [comment]
thanks!
