### ISSUE TITLE
Analog/Calibrate Example Incorrect circuit connetion 

### ISSUE THREAD

**Issue by Koler93** [arduino/docs-content#1617]
![image](https://github.com/arduino/docs-content/assets/104315501/d1a6a274-e369-4d72-ac5d-9f820b369f78)
 A0(Yellow line) should be connected to i10 and GND (black line) port of arduino to i13 on breadboard.

**Comment by jhansson-ard** [comment]
Hello @Koler93! Please include a link to the tutorial where you found this issue, so that we can take a look and work on a solution.

Thank you! ⭐

**Comment by Koler93** [comment]
https://docs.arduino.cc/built-in-examples/analog/Calibration here is the link to tutorial, I forgot to inlcude when i was opening issue.

**Comment by pedromsousalima** [comment]
https://github.com/arduino/docs-content/pull/1747 the circuit has been fixed on this PR.
Thank you for the feedback!
