### ISSUE TITLE
Servo Example Schematic Missing Ground Link

### ISSUE THREAD

**Issue by gh3597** [arduino/docs-content#1644]
https://github.com/arduino/docs-content/tree/main/content/learn/04.electronics/05.servo-motors

Seems to be no link in the image to tie the servo and Arduino ground together and no note mentioning this in the article either.

**Comment by karlsoderby** [comment]
Hello @gh3597 , to me it looks like the ground wires are connected via the (-) row on the breadboard. Could you maybe highlight this in the circuit itself? Thanks a lot!

**Comment by gh3597** [comment]
Looks like it's been edited/fixed since I made this report.
