### ISSUE TITLE
url issue

### ISSUE THREAD

**Issue by Giuseppe7887** [arduino/docs-content#1732]
on your website every url for micropython firmware lead to empty page, an example: https://docs.arduino.cc/micropython/ARDUINO_NANO_RP2040_CONNECT-20240105-v1.22.1.uf2

**Comment by jhansson-ard** [comment]
We'll get on this right away, thank you @Giuseppe7887 for the issue report! ⭐

**Comment by jhansson-ard** [comment]
@Giuseppe7887 The links should work properly again. Thanks again for your feedback!
