### ISSUE TITLE
Broken Store link in IoT Smart Garden Setup with Nano RP2040 Connect

### ISSUE THREAD

**Issue by RyanLua** [arduino/docs-content#1760]
On the [IoT Smart Garden Setup with Nano RP2040 Connect](https://docs.arduino.cc/tutorials/plant-watering-kit/iot-smart-garden-setup-with-nanorp2040/#hardware--software-needed) tutorial the link for the [Arduino Plant Watering Kit](https://store.arduino.cc/plant-watering-kit) is broken and leads to a 404 page.

![image](https://github.com/arduino/docs-content/assets/80087248/a6c38dad-08ba-4146-8c2c-0ddfd8f29688)
![image](https://github.com/arduino/docs-content/assets/80087248/ae022b2d-8b92-4335-888e-79cd6cddbc77)

On another note, I can't find where to buy the kit for the tutorial. I've searched Amazon and Arduino Store and could not find the official kit.

**Comment by jhansson-ard** [comment]
Hello @RyanLua!

Unfortunately, the kit is out of stock at the moment at our store and our resellers. 

Until we have it back, you are more than welcome to check out the secondary option of materials in the same tutorial.

I will update the link in the tutorial as well to show this.

Thank you! ⭐
