### ISSUE TITLE
makeyouruno.arduino.cc is not easily accessible from the Make Your Uno Docs page

### ISSUE THREAD

**Issue by chingyenyang** [arduino/docs-content#1765]
# Identified Area for Improvement

As a DIY kit, clear instructions for assembling the Make Your Own UNO Kit (SKU AKX00037) forms a large portion of the value proposition for this kit. On the box itself, I can see that a link for instruction is provided: https://makeyouruno.arduino.cc/

However, the Docs page for this product does not reflect this message clearly. There is no clear mention of this web page. While looking for instruction, I found there is a button that links to this step by step guide on DIY kit website. And I identify these two potential issues during the exploration. Firstly, the button colour blends into the background. Seccondly, the text itself (get started) is not descriptive enough to show here can be linked to instruction.

<img width="1036" alt="Screenshot 2024-02-16 at 10 58 31 PM" src="https://github.com/arduino/docs-content/assets/160281459/353a7a84-32b0-49fc-b6c8-edc0ac8445fe">

It is important to combine both the user experience and the communication of the brand values to make sure that the guide is clearly expressed and that users can intuitively and effortlessly can find it from the documentaion.

# Proposed solution

- The text of the button is changed to specifically state '3D Step by Step Guide'
- The colour of the button is changed to another color so that would act as a call to action.
- The button can keep with same colour, but add the augmented feature in it. So the button bring users naturally to click on

**Comment by jhansson-ard** [comment]
Hello @chingyenyang!

We will keep your feedback into account for upcoming fixes and changes to the website. Since I will have this followed in my own backlog of features, I will close this issue.

Thank you again!
