### ISSUE TITLE
Incorrect Schematic in Tutorials: Analog Input in 

### ISSUE THREAD

**Issue by theolaos** [arduino/docs-content#1790]
The page is [this](https://docs.arduino.cc/tutorials/uno-rev3-smd/AnalogInput/).

There is a small section where it says "Schematic" but immediately after that, there is just a circuit image of the potentiometer.

And then it says that the schematic of the photo-resistor, but the image that follows clearly says it is about the potentiometer.
 

<img width="500" src="https://github.com/arduino/docs-content/assets/92591390/e4525c8e-183d-4090-89ba-c511f589416a">

**Comment by jhansson-ard** [comment]
Thank you @theolaos, we will make sure to fix this ⭐
