### ISSUE TITLE
Incorrect (swapped) schematics in Servo tutorial

### ISSUE THREAD

**Issue by dnlombard** [arduino/docs-content#1802]
The servo tutorial, https://docs.arduino.cc/learn/electronics/servo-motors/, has 2 schematics, one for the 'Knob' example and another for the 'Sweep' example. The two schematics are swapped.

**Comment by jhansson-ard** [comment]
Hello @dnlombard! There is already a PR waiting for review [here](https://github.com/arduino/docs-content/pull/1794).

Thank you for your opened issue anyway!

**Comment by dnlombard** [comment]
Thank you!
