### ISSUE TITLE
Images not being displayed on official website

### ISSUE THREAD

**Issue by Lawrence4U** [arduino/docs-content#1876]
None of the images from the docs are displaying on the website view. The markdown inside the github repo works just fine.
https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoToBreadboard/ 
![image](https://github.com/arduino/docs-content/assets/60020067/17d274b8-3fae-469e-8940-cf457da70a4f)

I have checked only a couple of pages and on both no images where displayed. This happens both on chrome and edge regardless of adblocks etc.

**Comment by jhansson-ard** [comment]
Hello @Lawrence4U and thank you for your opened issue! 

We are aware of the problem, and we're working on a solution. This will be solved as swiftly as we can ⭐

**Comment by jhansson-ard** [comment]
This is now fixed @Lawrence4U, thanks for your issue report ⭐
