### ISSUE TITLE
Schematic drawing instantiate a common cathode RGB

### ISSUE THREAD

**Issue by mattinew** [arduino/docs-content#226]
In built-in-examples/communication/ReadASCIIString schematic drawing a common cathode RGB LED is instantiated, while both in _Hardware Required_ and in _Code_ sections a common anode is intended.

**Comment by marqdevx** [comment]
Thanks @mattinew for spotting the issue!
We are on it ✏️

**Comment by marqdevx** [comment]
Fix merged
Thanks for the report! @mattinew 😄
