### ISSUE TITLE
Wrong tranceiver mentioned in datasheet [TC-332]

### ISSUE THREAD

**Issue by pdnr7** [arduino/docs-content#237]
Arduino Portenta Machine Control Datasheet Page number 12,RS232/RS422/RS485 is mentioned wrong
![Capture](https://user-images.githubusercontent.com/47171382/145676704-d4c4a22d-dab6-4f1a-920c-0fd552391816.JPG)

**Comment by jhansson-ard** [comment]
@lunnea do you have time to look into this? ⭐
