### ISSUE TITLE
Tutorial appears to suggest a 10 second update period into TTN. 

### ISSUE THREAD

**Issue by StuartsProjects** [arduino/docs-content#279]
The tutorial on sending data to Arduino IOT via TTN has a test program with this suggested setup;

"This will just be a counter that updates every 10 seconds, to see if the data can be successfully sent from end device to the Arduino Cloud via the The Things Network"

Doe this mean you are suggesting a 10 second update period into TTN is OK ?

That rapid update period would be a significant brach of the TTN fair access policy if it were to be used all the time.

**Comment by karlsoderby** [comment]
Hi there @StuartsProjects 👋 an update of this article is in progress, where we have adjusted it to the [TTN limitations policy](https://www.thethingsnetwork.org/docs/lorawan/limitations/). Thank you for spotting this error and have a nice day. 

See fixes at (#334)
