### ISSUE TITLE
Style Guide link in CONTRIBUTING.md broken

### ISSUE THREAD

**Issue by gvenzl** [arduino/docs-content#288]
The link to the Style Guide in [CONTRIBUTING.md](https://github.com/arduino/docs-content/blob/main/CONTRIBUTING.md#style) refers to https://docs.arduino.cc/hacking/software/ArduinoStyleGuide which no longer exists:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/4610293/173196454-4175d54f-e3cc-49dc-afed-f52ddc9b83e6.png">

**Comment by per1234** [comment]
@jhansson-ard can this be considered resolved by https://github.com/arduino/docs-content/pull/290, or are you planning to also set up a redirect from https://docs.arduino.cc/hacking/software/ArduinoStyleGuide to https://docs.arduino.cc/learn/contributions/arduino-writing-style-guide?

**Comment by jhansson-ard** [comment]
@per1234 there is a redirect in a PR, awaiting review from @marqdevx ⭐

**Comment by jhansson-ard** [comment]
This link is now redirecting properly. Thank you for your eagle eyes @gvenzl 👀

**Comment by gvenzl** [comment]
You are welcome! :)
