### ISSUE TITLE
ide-v2-uploading-a-sketch.md steps are out of order

### ISSUE THREAD

**Issue by kuhrusty** [arduino/docs-content#300]
After following the instructions in https://docs.arduino.cc/software/ide-v2/tutorials/getting-started/ide-v2-downloading-and-installing on Linux, I'm looking at https://docs.arduino.cc/software/ide-v2/tutorials/getting-started/ide-v2-uploading-a-sketch; step 3 is:

> 3. Click on the verify tool (checkmark). Since we are verifying an empty sketch, we can be sure it is going to compile. After a few seconds, we can see the result of the action in the console (black box in the bottom).

On my box, instead of success, I get:

```
Compilation error: Missing FQBN (Fully Qualified Board Name)
```

I guess that means I needed to select a board first?  If I follow step 4 ("select the board that we are using"), and *then* go back to step 3, step 3 works.

(You can't quite just swap the two steps as written; they'll need to be massaged a bit.)

**Comment by karlsoderby** [comment]
Hey @kuhrusty I have addressed this issue in the documentation, switching the steps and "massaged" the text a bit 😄 Thank you for reporting it.
