### ISSUE TITLE
Incorrect schematic / diagram

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/docs-content#306]
The schematic [here](https://github.com/arduino/docs-content/blob/main/content/built-in-examples/02.digital/tonePitchFollower/tonePitchFollower.md) ([as published](https://docs.arduino.cc/built-in-examples/digital/tonePitchFollower)) is not correct.  The description and source code all indicate the speaker is connected to pin 9.

The breadboard diagram is incorrect.  The blue wire from pin 9 does not reach the resistor.

**Comment by marqdevx** [comment]
@jhansson-ard Could you please take care of this one?
Just move the pin8 to pin9 😄 
(You can also swap the wires of the speaker for better alignment)
![image](https://user-images.githubusercontent.com/11246294/175918426-00b0f25a-84d1-4b52-9dd8-7cd95e03ebd7.png)

**Comment by jhansson-ard** [comment]
Added a new PR, and tried to make @Coding-Badly a co-author (not sure it worked?)! 

Thanks for the eagles eyes @Coding-Badly 🦅

**Comment by marqdevx** [comment]
Yes you did, check it out here https://github.com/arduino/docs-content/pull/310/commits/7ab7c0deec28b542e8f6f744aa99225342229dd4

**Comment by Coding-Badly** [comment]
> tried to make @Coding-Badly a co-author (not sure it worked?)!

I have review permission.

> Thanks for the eagles eyes @Coding-Badly eagle

The corrections were spotted by and reported to me by [riopstop21](https://forum.arduino.cc/u/ripstop21).  I am merely the messenger.
