### ISSUE TITLE
VisionShield Camera exmaple image problem [PC-953]

### ISSUE THREAD

**Issue by avsteele** [arduino/docs-content#352]
The code in the example at https://docs.arduino.cc/tutorials/portenta-vision-shield/getting-started-camera does not appear to work as-is. The image is distorted, see attached. This is first reported in #161.

![image](https://user-images.githubusercontent.com/25284525/179231212-3a88d95f-4942-401e-8054-3a9b558df0dc.png)

I don't think the error is in the `Processing` code. `Serial.write` return value reports sending the expected # of bytes (78300) but at the other end I only receive 75228 (3072 too few). I verified this with PuTTY, and a `.Net` serial monitoring program. I can't tell if the bug is in the example, the Arduino libraries or something else

When looking at the data coming over the serial connection I see it come over in byte chunks of 16384 x 4 then one chunk of 8192. I think is possible and supported by the image that for each of the first 4 chunks 768 bytes are being lost in transmission. That's what makes the image look like that.

It is possible this is a Windows-specific issue.

This seems like a pretty basic test of the hardware. Are there any working examples using the camera out there at the moment? I only see ones using OpenMV.

**Comment by jcarolinares** [comment]
related with https://github.com/arduino/docs-content/issues/161 and solved some time ago by @marqdevx 

Thank you all!

Closed
