### ISSUE TITLE
Capacitor values not listed Arduino Portenta 

### ISSUE THREAD

**Issue by PrasanthElavarthi** [arduino/docs-content#363]
Hi. The values of C87 and C88 (**Antenna Matching Network**) is not given in the schematics. Can someone please tell those values.

**Comment by jhansson-ard** [comment]
@PrasanthElavarthi @per1234 in what tutorial or placement was this issue found? ⭐

**Comment by jcarolinares** [comment]
Hello @PrasanthElavarthi can you tell us in which Portenta model? Portenta X8, H7 or C33? Thanks!

**Comment by jcarolinares** [comment]
Not having an answer during the last month and taking into consideration the initial date of the issue we can mark this issue as closed!

thank you so much @PrasanthElavarthi for your feedback, we will take it into account for all the Portenta Family of boards!
