### ISSUE TITLE
Arduino Nano 33 BLE pinout and schematics are incorrect [MKC-559]

### ISSUE THREAD

**Issue by kckemper** [arduino/docs-content#364]
At least the mapping for A0 is wrong in both the pinout diagram and the schematic.

- The pinout labels it as A0->AIN[0]
- The schematic labels it as A0->AIN[3]
- The NINA-B3 datasheets list it mapping to A0->AIN[2] (this is correct)

Pleas check over and update the schematic and pinout diagram with the correct part mapping.

**Comment by kengdahl** [comment]
I look to me like A0 is still associated with AIN3. I have dropped a mention about this on our internal HW slack channel and hopefully the Schematics will be updated soon.

**Comment by kengdahl** [comment]
I have asked @agdl and @charlesbones to check the Schematics and they seem to be correct now. I'm closing this issue.
