### ISSUE TITLE
Uno WiFI Rev 2 - Tech Specs - Input voltage limit [TC-330]

### ISSUE THREAD

**Issue by Bylund** [arduino/docs-content#368]
https://store.arduino.cc/arduino-uno-wifi-rev2

Hi, according to the Arduino Uno WIFI Rev 2 tech specs the upper input voltage limit is 12V. Compared to other boards this seem low. According to the schematics it is using a MPM3610  step-down converter capable of up to 21V input. I am guessing the actual Input Voltage (limit) should be 6-20V like the other UNO's?

**Comment by karlsoderby** [comment]
Hi @Bylund this issue has now been adressed via (#434). Sorry for the long delay! 

@per1234 I have also opened a request to the store team to update the page.
