### ISSUE TITLE
EEPROM.length() documentation [MKC-557]

### ISSUE THREAD

**Issue by jarekgol** [arduino/docs-content#370]
Hi! There is no EEPROM.length() documentation on www site https://www.arduino.cc/en/Reference/EEPROM , but you use it in examples (eg. "EEPROM Read" https://www.arduino.cc/en/Tutorial/EEPROMRead )
I think you should add description to library reference.
Jarek

**Comment by karlsoderby** [comment]
Hey @jarekgol, better late than never, but this issue has now been solved (#393). Thank you for reporting it! 🙏
