### ISSUE TITLE
Link to Portenta Datasheet broken

### ISSUE THREAD

**Issue by wero1414** [arduino/docs-content#751]
When i click to download the datasheet i got a Page not found.

https://docs.arduino.cc/hardware/portenta-h7
![image](https://user-images.githubusercontent.com/15166625/210438075-96d19b8c-d820-40fb-87a4-97203c2ea6fd.png)

with this URL = https://docs.arduino.cc/static/4cda27067a048e59bc93c31edc5efc1a/ABX00042-ABX00045-ABX00046-datasheet.pdf

**Comment by akash73** [comment]
confirmed here. 
links on Portenta H7 lite and Portenta Lite Connected (that are the same as for H7) work. 
Here's the right link https://docs.arduino.cc/static/8b12393ba695296f668d69d469d04d3f/ABX00042-ABX00045-ABX00046-datasheet.pdf

**Comment by jhansson-ard** [comment]
The current link on Portenta H7 works, I will close this issue now. Please let us know if there are any more issues! ⭐
