### ISSUE TITLE
Page Expansion on portenta X8

### ISSUE THREAD

**Issue by miqroskunk** [arduino/docs-content#805]
Portenta X8 has the "+" at the bottom of the page to then show the connection status and factory name. This is also where to find "LAUNCH SHELL" which is not discussed at all in the open the box documentation. Needs a section on the open the box page this took me hours to find.

**Comment by akash73** [comment]
Thanks @miqroskunk for pointing out. we are gonna release a new version of the manual, and we'll cover it.
